name: wanAndroid
description: WanAndroid 客户端 Flutter版.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter:  ^2.0.10
  shared_preferences: ^2.0.6
  dio: 4.0.4
  dio_cookie_manager: 2.0.0
  pull_to_refresh: 2.0.0
  event_bus: 2.0.0

  path_provider: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

